apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-helloworld
  labels:
    app: {{ .Release.Name }}-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-helloworld
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-helloworld
    spec:
      containers:
      - name: helloworld
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8088
